cmake_minimum_required(VERSION 3.8)
project(android_interfaces)

find_package(ament_cmake REQUIRED)

# Uncomment this only when the first interface is added:
#
# find_package(rosidl_default_generators REQUIRED)

# To add your interfaces uncomment the block below and list them here:
#
# rosidl_generate_interfaces(${PROJECT_NAME}
#   # "msg/Example.msg"
#   # "srv/Example.srv"
#   # "action/Example.action"
# )

ament_package()
